AllCops:
  TargetRubyVersion: 2.7

Bundler/OrderedGems:
  Description: Gems should be alphabetically sorted within groups.
  Enabled: false

Layout/AccessModifierIndentation:
  Description: Modifiers should be indented as deep as method definitions,
    or as deep as the class/module keyword, depending on configuration.
  EnforcedStyle: outdent

Layout/EmptyLinesAroundAttributeAccessor:
  Description: Keep blank lines around attribute accessors.
  Enabled: true

Layout/HeredocIndentation:
  Description: Checks the indentation of the here document bodies.
  Enabled: false

Layout/LineLength:
  Description: Checks the length of lines in the source code.
  AllowURI: true
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Description: Checks method call operators to not have spaces around them.
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Description: Use spaces inside hash literal braces - or don't.
  StyleGuide: https://github.com/rubocop-hq/ruby-style-guide#spaces-operators
  EnforcedStyle: no_space

Lint/AmbiguousRegexpLiteral:
  Description: Checks for ambiguous regexp literals in the first argument of a method invocation without parentheses.
  Exclude:
    - "features/**/*_steps.rb"
    - "spec/**/*_steps.rb"
    - "tmp/**/*_steps.rb"

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Description: Don't use algorithm constants for `OpenSSL::Cipher` and `OpenSSL::Digest`.
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/DuplicateRescueException:
  Enabled: true

Lint/EmptyConditionalBody:
  Enabled: true

Lint/FloatComparison:
  Enabled: true

Lint/MissingSuper:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Description: Do not mix named captures and numbered captures in a Regexp literal.
  Enabled: true

Lint/OutOfRangeRegexpRef:
  Enabled: true

Lint/RaiseException:
  Description: Checks for `raise` or `fail` statements which are raising `Exception` class.
  Enabled: true

Lint/SelfAssignment:
  Enabled: true

Lint/StructNewOverride:
  Description: Disallow overriding the `Struct` built-in methods via `Struct.new`.
  Enabled: true

Lint/TopLevelReturnWithArgument:
  Enabled: true

Lint/UnreachableLoop:
  Enabled: true

Metrics/AbcSize:
  Description: Checks that the ABC size of methods is not higher than the configured maximum.
  Max: 15

Metrics/BlockLength:
  Description: Checks if the length of a block exceeds some maximum value.
  Exclude:
    - "spec/**/*.rb"

Metrics/BlockNesting:
  Description: Avoid excessive block nesting.
  StyleGuide: https://github.com/rubocop-hq/ruby-style-guide#three-is-the-number-thou-shalt-count
  Max: 2

Metrics/ClassLength:
  Max: 300

Metrics/MethodLength:
  Description: Checks if the length of a method exceeds some maximum value.
  CountComments: false
  Max: 13

Metrics/ParameterLists:
  Description: Avoid parameter lists longer than three or four parameters.
  StyleGuide: https://github.com/rubocop-hq/ruby-style-guide#too-many-params
  Max: 4
  CountKeywordArgs: true

Style/AccessorGrouping:
    Enabled: true

Style/ArrayCoercion:
    Enabled: true

Style/BisectedAttrAccessor:
    Enabled: true

Style/CaseLikeIf:
    Enabled: true

Style/CollectionMethods:
  Description: Enforces the use of consistent method names from the Enumerable module.
  PreferredMethods:
    map: "collect"
    reduce: "inject"
    find: "detect"
    find_all: "select"

Style/Documentation:
  Description: Checks for missing top-level documentation of classes and modules.
  Enabled: false

Style/DoubleNegation:
  Description: Checks for uses of double negation (!!).
  StyleGuide: https://github.com/rubocop-hq/ruby-style-guide#no-bang-bang
  Enabled: false

Style/ExplicitBlockArgument:
    # capturing as a proc has a performance hit, so is a case by case choice
    Enabled: false

Style/ExponentialNotation:
  Description: When using exponential notation, favor a mantissa between 1 (inclusive) and 10 (exclusive).
  Enabled: true

Style/FrozenStringLiteralComment:
  Description:
    Add the frozen_string_literal comment to the top of files to help transition
    from Ruby 2.3.0 to Ruby 3.0.
  Enabled: true
  EnforcedStyle: always
  Exclude:
    - "spec/fixtures/**/*"

Style/GlobalStdStream:
    Enabled: true

Style/GuardClause:
  Description: Use a guard clause instead of wrapping the code inside a conditional expression.
  Enabled: false

Style/HashAsLastArrayItem:
    Enabled: true

Style/HashEachMethods:
  Description: Use Hash#each_key and Hash#each_value.
  Enabled: true

Style/HashLikeCase:
    Enabled: true

Style/HashTransformKeys:
  Description: Prefer `transform_keys` over `each_with_object` and `map`.
  Enabled: true

Style/HashTransformValues:
  Description: Prefer `transform_values` over `each_with_object` and `map`.
  Enabled: true

Style/HashSyntax:
  Description: Checks hash literal syntax.
  EnforcedStyle: ruby19

Style/OptionalBooleanParameter:
    Enabled: true

Style/RedundantAssignment:
    Enabled: true

Style/RedundantFetchBlock:
    Enabled: true

Style/RedundantFileExtensionInRequire:
    Enabled: true

Style/RedundantRegexpCharacterClass:
  Description: Checks for unnecessary single-element Regexp character classes.
  Enabled: true

Style/RedundantRegexpEscape:
  Description: Checks for redundant escapes in Regexps.
  Enabled: true

Style/RegexpLiteral:
  Description: Use / or %r around regular expressions.
  StyleGuide: https://github.com/rubocop-hq/ruby-style-guide#percent-r
  Enabled: false

Style/SingleArgumentDig:
    Enabled: true

Style/SlicingWithRange:
  Description: Checks array slicing is done with endless ranges when suitable.
  Enabled: true

Style/StringConcatenation:
    Enabled: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: no_comma
